name: Publish
on:
  push:
    tags:
      - "*"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "10"

      - name: Install npm dependencies
        run: npm ci

      - name: Set up .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc
        env:
          NPM_AUTH_TOKEN: "${{ secrets.NPM_AUTH_TOKEN }}"

      - name: Publish on npm
        run: npm publish
